### ISSUE TITLE
Toolgun Bug

### ISSUE THREAD

**Issue by GregoryTwix** [Facepunch/garrysmod-issues#1854]
When I try to construct something whenever on DarkRP or singleplayer and after some time of play game changes my weapon to toolgun. Its being fixed (for a while) if I will restart the game.

Example: http://youtu.be/DTQnH6s2SV8

I am not clicking anything on keyboard except for 1,2,3,4 to try to change weapon in other way.
It started occuring after last update.

Update, when I drop the toolgun everything is normal back. If I will pick it up once more same error will occur.

Example: https://www.youtube.com/watch?v=P61eW4epRYw&feature=youtu.be
Still, not clicking anything

**Comment by robotboy655** [comment]
It is already fixed for next update.
You can fix this for yourself by copying the changes from this commit:
https://raw.githubusercontent.com/garrynewman/garrysmod/24bb5413487dcba5ea313e7316cfd7090be78815/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/cl_init.lua

to your garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/cl_init.lua

**Comment by GregoryTwix** [comment]
problem still occurs even tho I pasted whole script from here.

**Comment by robotboy655** [comment]
try changing the 0.1 to 1?

**Comment by robotboy655** [comment]
It will only work in single player.

**Comment by GregoryTwix** [comment]
So I guess that server owner need to change this right?

**Comment by robotboy655** [comment]
Yes.

**Comment by robotboy655** [comment]
You can still try it in singleplayer.
