### ISSUE TITLE
Game crashes/freezes trying to apply decals on complex meshes.

### ISSUE THREAD

**Issue by Hoffa1337** [Facepunch/garrysmod-issues#2566]
Complex models with a lot of polygons crashes the game when applying decals. This is bad. Robotboy655 knows what's up. 

Model that causes the crash:
http://puu.sh/onW67/cf74cda94d.zip 

Dumpfile:
http://puu.sh/onW3O/87143c0558.zip

I might or might not kidnap / buy you whisky if this gets/doesnt get fixed.

**Comment by robotboy655** [comment]
It's a common decal crash, nothing to do with traces.

**Comment by Hoffa1337** [comment]
Fix it.

**Comment by robotboy655** [comment]
Make me

**Comment by Hoffa1337** [comment]
Contemplating what will work best. Whisky or kidnapping.

**Comment by robotboy655** [comment]
Whoa Whoa, it's just a prank dude, just a prank!

**Comment by robotboy655** [comment]
Model's pretty bad, TF2 even refuses to load it.

**Comment by Hoffa1337** [comment]
You could blame the model but that won't make this problem go away. We have another 10 models with this level of detail we intend to use. It's not a big problem in our gamemode as there are no guns but I can only imagine the tears and salt on workshop when thousands of kids are suddenly crashing for no apparent reason after installing this. Can we get a way to disable decals completely on a specific model? I have another example from a battleship that has twice the polygons this model has and allthough it doesn't crash it makes the game look like your GFX card is having a seizure everytime a decal is applied.

**Comment by robotboy655** [comment]
I have already identified the problem and found a fix, but there are like 3 more new crashes with decals and your overdone models.

**Comment by Hoffa1337** [comment]
Out of curiosity, what was the problem? :)

**Comment by Hoffa1337** [comment]
Any workarounds for this? We're going to release the addons soon regardless if it's fixed or not and if there's no ETA to fix this we'll just link to this issue from workshop / in-game when you spawn the affected vehicles :smiling_imp:

**Comment by robotboy655** [comment]
Optimize your models to have less vertices. It seems that Source is not really meant to handle 2+ million vertices on a model.

**Comment by Hoffa1337** [comment]
It used to be more detailed. As stated previously higher end models have worked before this one without crashing from the decals. And where's the fun if we don't push the engine to its limit?

**Comment by Kefta** [comment]
While we're add it, can we support the same map dimensions as Source 2? Thanks

**Comment by robotboy655** [comment]
Should be fixed, but I had to go for the lame fix - to prevent decals from being created if they are about to crash the game.

There appears to be a billion crash problems with decals on models with too many vertices, and I am not willing to spend ages trying to figure them all out.

**Comment by goigle** [comment]
This is still happening: https://facepunch.com/showthread.php?t=1574345
