### ISSUE TITLE
Language settings

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2580]
I would suggest to translate the whole game if you select a language.
Like in Half-Life 2.

Things which would need a translation:
Spawnmenu
Contextmenu
Some Notifications
normal Optionsmenu(Translated in HL2 and other source games)
alternate Serverbrowser(Translated in HL2 and other source games)
NPC voices(Translated in HL2 and other source games)

It is some of the major things this game needs, in my opinion.

**Comment by Satton2** [comment]
Let me add some things in this list...

Missing strings:
1) 4 language files: https://i.imgur.com/T3AALjS.png
2) Player Model menu: https://i.imgur.com/guNv262.png
3) Prerealease branch text: https://i.imgur.com/7jqmeni.png
4) Options: https://i.imgur.com/QPreolO.png
• As I know, there is already translated localization file for this one somewhere in game files, but they are not used in game.
5) Spawnlists right click options: 
• https://i.imgur.com/Zbr3Ow0.png
• https://i.imgur.com/Sb6UYAD.png
6) «<something/addon name> is creating errors»: https://i.imgur.com/TiSokte.png

**Comment by Satton2** [comment]
Since the update will be released on September 3, and because this issue is open for about 3 years (also its last message was written about 5 months ago) it's a great time to remind @robotboy655 about its existence.

**Comment by Satton2** [comment]
I forgot about two important things!
Here they are:
7. Achievements: 
![image](https://user-images.githubusercontent.com/23385240/63895803-e1455300-c9f8-11e9-8779-540ca891ebe9.png)
8. Friends' statuses in the Steam friend list: 
![image](https://user-images.githubusercontent.com/23385240/63896029-98da6500-c9f9-11e9-82e3-0b5c057a0a01.png)

**Comment by Satton2** [comment]
Missing strings:
1. ![image](https://user-images.githubusercontent.com/23385240/69010247-94717880-0966-11ea-8e42-a7ac3fc98e50.png)
Original text: **Press \"Save Changes\" to save any changes made to your spawnlists\!**
2. ![image](https://user-images.githubusercontent.com/23385240/69010253-9e937700-0966-11ea-8e67-5d3c84c2e0fa.png)
Original text: **You can edit your spawnlists by drag and dropping icons around and inbetween spawnlists\!**
Where these strings can be found: **garrysmod/garrysmod/resource/localization/en/hints.properties**
2. ![image](https://user-images.githubusercontent.com/23385240/69010316-224d6380-0967-11ea-8f54-766740213e5b.png)
Original text: **Enable HEV Suit**
Note: This string is available on Crowdin but missing in the game.
Where this string can be found: **garrysmod/garrysmod/resource/localization/en/main_menu.properties**

@mcNuggets1 Could you please change the title of the issue to something like «Localization problems & Missing strings» so it will be more relevant to its current content?  Thank you in advance.

**Comment by robotboy655** [comment]
So here's progress:
* Stuff from your Nov 17, 2019 message was resolved a while ago
* Player model selector, and right menus have been translated
* So is the script error stuff

Things I am not interested in translating:
* Steam stuff: Achievements and Rich Presence
* `You are on a "x" branch` message - it is more a dev thing

**Comment by mcNuggets1** [comment]
Lua Stuff not being translated:
Weapon "bouncy" boxes with their information texts, like "Instructions, Purpose" etc and the default weapons GMod is shipped with.

Entities in Spawnmenu being all english still.
Also Categories etc.

C++ Stuff not being translated:
In the options menu: "Other"-tab, Keybindings in Keybindings tab

Also NPCs voices would be cool to be translated in other languages, like they are in some of the other source engine games would be neat.

**Comment by Satton2** [comment]
First of all, thank you for your work, Rubat.
Second, I want to do a little clean up to see what strings are still untranslatable, and what are not. Let's go:

Strings that are **still not translable on Crowdin**:
- 5 localization files: https://i.imgur.com/T3AALjS.png
-- **npc-ents_english** contains entities, weapons, vehicles, and NPCs names in respective tabs (_related to mcNuggets1 message regarding entities in spawnmenu_).
- Categories names in NPCs, Weapon, etc. tabs in spawnmenu (_thanks mcNuggets1_).
- Information related to weapons (_Instructions, Purpose, Authors_) and texts of the standard GMod weapons like Fists and the Manhack Gun ([view ](https://i.imgur.com/eUAHqAU.png)| _Thanks mcNuggets1_).
- Options menu (_translated but were not added on Crowdin. Plus, there are GMod specified options, keybindings, and tabs which are not translated_).
- Legacy server browser (_translated but were not added on Crowdin_).
- Download/extracting <_addonname_> + addon counter ([view](https://i.imgur.com/UR55PtN.png))

Not translatable strings that were rejected to add on Crowdin:
- Rich Presence (_hope this one will appear on Crowdin sometime_).
- Achievements (_hope this one will appear on Crowdin sometime_).
- Brach related information ([view](https://i.imgur.com/7jqmeni.png)).

By the way, Rubat, could you please add some "Help us translate Garry's Mod" button in the language selection panel that will lead to the Crowdin page? Somewhere here: [view](https://i.imgur.com/axo840H.png)
