### ISSUE TITLE
Gmod crashing left right and centre on ttt server with new update

### ISSUE THREAD

**Issue by Ytrewqcw** [Facepunch/garrysmod-issues#2971]
### Details
While playing ttt online, on a server of about 20 people a person is crashing on average every minute or 2. When I crashed there was no lag beforehand, it just happened out of the blue.

### Steps to reproduce
Play and it'll happen after a few minutes probably, happened on a ttt server online so that might be a part of it.
Hopefully I attached the right crash log.
[New Compressed (zipped) Folder.zip](https://github.com/Facepunch/garrysmod-issues/files/661176/New.Compressed.zipped.Folder.zip)

**Comment by willox** [comment]
I think there's an addon crashing you purposefully. Does this happen on any other servers?

**Comment by MinIsMin** [comment]
For me everything works.

Seems like "Realsnow" is acting weird. You should update to current version 1.1.4.
```
RealSnow:  RealSnow released!
Remember to update to version 1.1!
ERROR: Trying to derive entity realsnow_snowball from non existant entity base_gmodentity!
```

**Comment by MinIsMin** [comment]
This crash and #2975 throw this exception:
(Seems to be Windows only)
```
StreamType ExceptionStream
Location: 
	DataSize 168
	RVA 240
DirectoryData: 
	ThreadId 6228
	__alignment 0
	MINIDUMP_EXCEPTION: 
		ExceptionCode EXCEPTION_ACCESS_VIOLATION
		ExceptionFlags EXCEPTION_CONTINUABLE
		ExceptionRecord 0
		RelatedExceptionRecord None
		ExceptionAddress 1764717157
		NumberParameters 2
		__unusedAlignment 0
			8
			1764717157
	ThreadContext: 
		DataSize 0
		RVA 0
```

**Comment by Bo98** [comment]
Stack trace looks different though.

**Comment by Thendon** [comment]
I have the same problem on my server. Ytrewqcw can you add me on steam?

**Comment by Violat0r** [comment]
I have gotten reports from many people that play on my servers that they are crashing and not just on my servers after the update.

http://dumps.metastruct.uk.to/dumper.py?dump=hl2_161216_crash_2016_12_19T22_59_2C0.mdmp

http://dumps.metastruct.uk.to/dumper.py?dump=hl2_161220_crash_2016_12_20T21_37_46C0.mdmp

**Comment by Ytrewqcw** [comment]
I'm not the owner of the server or even an admin, so I can't test what works. I only made the report because I hoped it was an issue with Gmod, and it would be fixed quicker if I made a report. The owner of the server is testing for whats causing crashes, but I dont think he knows whats happening yet.

**Comment by lopy67** [comment]
My game crashes and I'm on Mac. I got a low fps script to try stop it from crashing but it didn't help. Its really annoying.

**Comment by Thendon** [comment]
Seems to be the real snow addon.

**Comment by Violat0r** [comment]
Can confirm, removed real snow from one of our servers and people stopped crashing on it.

**Comment by robotboy655** [comment]
Is it a workshop addon? Can you post a link to it?

**Comment by MinIsMin** [comment]
https://scriptfodder.com/scripts/view/3219

**Comment by robotboy655** [comment]
Well can't help you with that, you will have to contact the author of the addon.

**Comment by ZachPL** [comment]
This is still crashing gmod, is this an issue with material:settexture?

**Comment by robotboy655** [comment]
Marking this as solved, the 2 crash dumps from @Violat0r point to a crash that has been fixed in the Dev branch and in the next update.

**Comment by ZachPL** [comment]
Still getting crashes with this addon after todays update, here is a crash log a user sent me

[hl2_171212_crash_2017_12_19T3_0_29C0.zip](https://github.com/Facepunch/garrysmod-issues/files/1570218/hl2_171212_crash_2017_12_19T3_0_29C0.zip)

**Comment by willox** [comment]
You mean the RealSnow addon? Are you able to reproduce it easily? It seems to be related to bullet impacts hitting a surface (probably that snow.)

**Comment by zhulb001** [comment]
Yes, sorry I mean the realsnow addon. I put it back on the server after the december update and each time I have with in a few minutes people have reported to me that they are crashing. Seems to happen every time so I assume it would be easily reproduced. Someone else in the discussion of the addon said it's happening to them too.

It's good to know that it is likely the bullet impacts though, I'll probably disable the snow falling tonight to see if it keeps happening. Thanks!

**Comment by ZachPL** [comment]
Yes, sorry I mean the realsnow addon. I put it back on the server after the december update and each time I have with in a few minutes people have reported to me that they are crashing. Seems to happen every time so I assume it would be easily reproduced. Someone else in the discussion of the addon said it's happening to them too.

It's good to know that it is likely the bullet impacts though, I'll probably disable the snow falling tonight to see if it keeps happening. Thanks!
