### ISSUE TITLE
Entity indexes can vary (new update)

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3991]
### Details
The update introduced a new annoying bug, which breaks every addon using entity indexes for map entities.
The entity indexes are different now, when the map is changed and when the server started for the first time.
This breaks darkrp's door system.

I'm on dev branch, dedicated server, rp_bangclaw.
A mapchange fixes this.

### Steps to reproduce
Start a dedicated server with the map rp_bangclaw.
Print yourself a table of all entities, look at their ids. (The ids of the prop_door_rotating entities at 600-700~)
Change the map. (Now the ids are in the order they were before the update and correctly)
Print yourself a table again. (See that the ids changed)

**Comment by Jvs34** [comment]
But isn't [MapCreationID](http://wiki.garrysmod.com/page/Entity/MapCreationID) what you're supposed to use? Or is there something that stops people from using that function instead of straight indexes?

**Comment by mcNuggets1** [comment]
Oh yeah, sorry.
That's whats actually used inside DarkRP.
The MapCreationIDs are mixed up, after the server started, that's the issue then.

**Comment by mcNuggets1** [comment]
Yeah, they are different.

prop_door_rotating near the police department:
first start: 1432
after mapchange (no matter how many): 1434 (correct id)

**Comment by deadmonstor** [comment]
I have tried to replicate this but cannot get it to happen for me.

Code used lua_run for k,v in pairs(ents.FindByClass("prop_door_rotating")) do print(tostring(v:GetPos()) .." " ..v:MapCreationID()) end

The results below show what I got for all of the following. This was done on dev branch and stable branch and they provided the same results
SANDBOX: 
	gm_construct -> rp_bangclaw
	rp_bangclaw -> rp_bangclaw
	rp_bangclaw -> gm_construct -> rp_bangclaw

DarkRP: 
	gm_construct -> rp_bangclaw
	rp_bangclaw -> rp_bangclaw
	rp_bangclaw -> gm_construct -> rp_bangclaw

Results if you want to compare: https://pastebin.com/raw/DkUAax0F

**Comment by mcNuggets1** [comment]
This was tested on a dedicated servers with addons.
Before the update, these issues did not occur.
In my listen server everything works fine.

**Comment by robotboy655** [comment]
Should be fixed in Dev, sorry about that.

**Comment by mcNuggets1** [comment]
This isn't live right?
So I have to go on dev branch with my server again, right?

**Comment by robotboy655** [comment]
It was only broken on Dev, and it is fixed on Dev.

**Comment by mcNuggets1** [comment]
Ohhh. Thanks for the info.

**Comment by mcNuggets1** [comment]
Actually.
I've updated my server to the main branch and the issue there still occurs.
I'm gonna update the server to the dev branch then.

**Comment by mcNuggets1** [comment]
It's happening on base branch for me too, several verified game cache.
But the issue there is different, first server map start, everything is fine, map change => MapCreationIDs differ
