### ISSUE TITLE
Sprinting doesnt always work while holding down the Sprint key

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#4048]
### Details
In the dev branch, sprinting may cease working after you jumped, used no clip, while sprinting.
You have to press the sprint button again then.

### Steps to reproduce
Most likely unknown but only happens on dev version

**Comment by robotboy655** [comment]
Can you reproduce this since https://github.com/Facepunch/garrysmod-issues/issues/4040 was fixed?

Do you mean crouching stops your sprinting?

**Comment by mcNuggets1** [comment]
Yeah still happening, local game, multiplayer.

Crouching is the issue.

**Comment by robotboy655** [comment]
Should work as it did before now. Let me know if there are any other issues that arise.

**Comment by robotboy655** [comment]
Currently only on Dev.
