### ISSUE TITLE
RichText VGUI element InsertClickableText not working

### ISSUE THREAD

**Issue by Earu** [Facepunch/garrysmod-issues#4358]
I've been experiencing a very weird behavior with the RichText component.
Example below, because I'm not sure how to phrase it:
![example](https://i.imgur.com/LIYs3aP.gif)

Here's the code I use for appending text that contains links onto a RichText panel
```lua
	local function get_url(str)
		local patterns = {
			"https?://[^%s%\"%>%<]+",
			"ftp://[^%s%\"%>%<]+",
			"steam://[^%s%\"%>%<]+",
			"www%.[^%s%\"]+%.[^%s%\"]+"
		}

		for _, pattern in ipairs(patterns) do
			local start_pos, end_pos = str:find(pattern, 1, false)
			if start_pos then
				return start_pos, end_pos
			end
		end

		return false
	end

	local function append_text(richtext, text)
		richtext:AppendText(text)
	end

	local function append_text_url(richtext, text)
		local start_pos, end_pos = get_url(text)
		if not start_pos then
			append_text(richtext, text)
		else
			local url = text:sub(start_pos, end_pos)
			append_text(richtext, text:sub(1, start_pos - 1))
			richtext:InsertClickableTextStart(url)
			append_text(richtext, url)
			richtext:InsertClickableTextEnd()

			-- recurse for possible other urls after this one
			append_text_url(richtext, text:sub(end_pos + 1))
		end
	end
```

Tested on 64x and default branch, the problem happens on all of them. This bug was also confirmed by other developers trying to achieve similar things.

**Comment by robotboy655** [comment]
```
concommand.Add( "testgui",function( ply, cmd, args )
	-- Create a window frame
	TextFrame = vgui.Create("DFrame")
	TextFrame:SetSize(1450, 450)
	TextFrame:Center()
	TextFrame:SetTitle("RichText")
	TextFrame:MakePopup()

	-- RichText panel
	local richtext = vgui.Create("RichText", TextFrame)
	richtext:Dock(FILL)

	-- First segment
	richtext:InsertColorChange(255, 255, 255, 255)
	richtext:AppendText("This is a Rich Text panel — a panel used in Source MP's default chat box and developer console.\n\nSee the ")

	-- Second segment
	richtext:InsertColorChange(192, 192, 255, 255)
	richtext:InsertClickableTextStart("OpenWiki")	-- Make incoming text fire the "OpenWiki" value when clicked
	richtext:AppendText("Garry's Mod Wiki")
	richtext:InsertClickableTextEnd()	-- End clickable text here

	-- Third segment
	richtext:InsertColorChange(255, 255, 255, 255)
	richtext:AppendText(" for information on how to use a Rich Text panel.")

	for i = 0, 10 do
	append_text_url( richtext, ("a"):rep( math.random( 20, 40)  ) .. " https://wiki.facepunch.com/gmod/" ..  math.random( 1, 100) .. " "..  ("b"):rep( math.random( 20, 40)  ) .. " https://wiki.facepunch.com/gmod/" ..  math.random( 1, 100)  .. " "..  ("c"):rep( math.random( 20, 40)  ) .. " https://wiki.facepunch.com/gmod/" ..  math.random( 1, 100) .. " \n"  )
	end

	-- Background color
	function richtext:PerformLayout() self:SetBGColor(Color(32, 32, 46)) end
end )

```
Cannot reproduce the link issues with this code. You will need to provide a an actual example which actually reproduces the issue.

I do however see an issue with text highlighting.

**Comment by robotboy655** [comment]
I have made some changes on the Dev branch, you should try and see if it changes anything for you.

**Comment by Earu** [comment]
```lua
concommand.Add(
    "testgui",
    function(ply, cmd, args)
        -- Create a window frame
        local TextFrame = vgui.Create("DFrame")
        TextFrame:SetSize(1450, 450)
        TextFrame:Center()
        TextFrame:SetTitle("RichText")
        TextFrame:MakePopup()
        TextFrame:SetDraggable(false)

        -- RichText panel
        local richtext = vgui.Create("RichText", TextFrame)
        richtext:Dock(FILL)
        richtext.PerformLayout = function(self)
            richtext:SetFontInternal("Trebuchet24")
            richtext:InsertColorChange(50, 50, 50, 50)
        end

        -- First segment
        richtext:InsertColorChange(255, 255, 255, 255)
        richtext:AppendText(
            "This is a Rich Text panel — a panel used in Source MP's default chat box and developer console.\n\nSee the "
        )

        -- Second segment
        richtext:InsertColorChange(192, 192, 255, 255)
        richtext:InsertClickableTextStart("OpenWiki") -- Make incoming text fire the "OpenWiki" value when clicked
        richtext:AppendText("Garry's Mod Wiki")
        richtext:InsertClickableTextEnd() -- End clickable text here

        -- Third segment
        richtext:InsertColorChange(255, 255, 255, 255)
        richtext:AppendText(" for information on how to use a Rich Text panel.")

        for _ = 0, 10 do
            append_text_url(
                richtext,
                    ("a"):rep(math.random(20, 40)) ..
                    " https://wiki.facepunch.com/gmod/" ..
                    math.random(1, 100) .. " " ..
                    ("b"):rep(math.random(20, 40)) ..
                    " https://wiki.facepunch.com/gmod/" ..
                    math.random(1, 100) .. " " ..
                    ("c"):rep(math.random(20, 40)) ..
                    " https://wiki.facepunch.com/gmod/" ..
                    math.random(1, 100) .. " \n"
            )
        end
    end
)```

I managed to reproduce the issue with your code by changing your `PerformLayout` function. It seems that changing the font/color after appending a clickable text prevents you from clicking it. If you can't see the the odd behavior at first hand try scrolling, it should work.

**Comment by robotboy655** [comment]
Please test in your own test scenario the changes on Dev branch, I fixed no text being clickable with that example.

i also fixed selection issues with different fonts, and you can now select the clickable text fonts via `Panel.SetUnderlineFont( font )`

**Comment by Earu** [comment]
Sadly I still cannot click the text still using my code, however the selection works perfectly now. 

On another note im not sure if this intended but if you do not set a color on the RichText panel, the text becomes invisible:
![example](https://i.imgur.com/J90n0eE.png)
```lua
concommand.Add("testgui", function(ply, cmd, args)
	-- Create a window frame
	local frame = vgui.Create("DFrame")
	frame:SetTitle("RichText")
	frame:SetDraggable(true)
	frame:SetSizable(true)
	frame:SetSize(1450, 450)
	frame:Center()
	frame:MakePopup()

	-- RichText panel
	local richtext = frame:Add("RichText")
	richtext:Dock(FILL)
	--richtext.PerformLayout = function(self)
	--	self:InsertColorChange(255,255,255,255)
	--end

	for _ = 0, 10 do
		append_text_url(richtext,
			("a"):rep(math.random(20, 40))
			.. " https://wiki.facepunch.com/gmod/"
			..  math.random(1, 100) .. " "
			..  ("b"):rep(math.random(20, 40))
			.. " https://wiki.facepunch.com/gmod/"
			..  math.random(1, 100)  .. " "
			.. ("c"):rep( math.random(20, 40))
			.. " https://wiki.facepunch.com/gmod/"
			..  math.random(1, 100) .. " \n")
	end
end)
```

**Comment by robotboy655** [comment]
I can confirm it with your addon, seems to be related to resizing.

**Comment by robotboy655** [comment]
This took way too long, but it should be fixed on Dev.
