### ISSUE TITLE
Infinite Scrape sounds on Gibs and Lua Effects (Phys)

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#4499]
Infinite scrape sounds seem to play when Lua effects and Gibs (Explosive barrels, wooden boxes) disappear, Gibs seem to cause the infinite scrape sound on impact, not just removal.

This also seems to happen even if the entitys physical object is set to gmod_silent.

Unsure if this is to do with GM:EntityEmitSound but considering that's a hook i'm using it's possible.

This didn't happen before the newest update so i'm assuming something went wrong somewhere.

**Comment by robotboy655** [comment]
I know it's cool to blame everything on the updates, but please no.

This is likely duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4008

**Comment by MagentaIris** [comment]
That's what i was referencing yes, This never used to be a problem, So it is definitely an update issue, It's not "Cool" to blame it on an update that's just the most logical outcome of the issue since it wasn't a problem before the recent updates.

I can understand Lua effects, but normal prop gibs?

This is all in a multiplayer environment too.

**Comment by thegrb93** [comment]
Pac3 users were complaining about their clientside entities scraping and clattering sounds and I even heard a physics 'thud' after wearing my outfit too so I do think something is up with clientside physics.

**Comment by osiris-plus** [comment]
The issue with endless sounds of burning, scraping, vehicle engine has been there for ages. It's not recent.

**Comment by robotboy655** [comment]
Do you have a way to reproduce it on demand?
Do you know after which update it broke for you? (I still highly doubt it was a game update)

**Comment by robotboy655** [comment]
Also please try the Dev beta branch (on your client), I just fixed #4008.

**Comment by MagentaIris** [comment]
Still happens after the 22nd june update.

That update also broke a fuck ton of maps, nice.

Check it out - https://github.com/Facepunch/garrysmod-issues/issues/4374

**Comment by robotboy655** [comment]
Without any info on how to reproduce this (or any info at all, like already requested above) for your specific case I cannot do anything.

**Comment by MagentaIris** [comment]
```
function GLOBAL_EntityEmitSound(data)

	local SCALE = game.GetTimeScale()
	local PITCH = data.Pitch
	local LVL = data.SoundLevel
	local ENT = data.Entity
	local NAME = string.lower(data.SoundName)
	local CT = CurTime()
	
	if NAME == "common/wpn_hudoff.wav" then
	return false end
	
	if NAME:find("burnpain") then
	return false end

	if (SCALE != 1) then
		data.Pitch = math.Clamp(data.Pitch*(SCALE^0.5),20,230)
	return true end

end
hook.Add("EntityEmitSound","GLOBAL_EntityEmitSoundHook",GLOBAL_EntityEmitSound)
```

Have at it.

**Comment by robotboy655** [comment]
What gibs precisely? Lua created gibs? Just normal gibs from an explosion?
Singleplayer? Local MP? srcds? Am i running that code clientside or serverside?

I thought you said it was not related to EntityEmitSound anyway? I can't reproduce any issues with the code you provided with gibs from crates and the explosive barrels, both via clientside lua gibs and by just breaking/exploding hundreds of those props.

**Comment by MagentaIris** [comment]
Shared.
Multiplayer.
Base Gmod Branch.

Oildrum explosions create gibs upon being destroyed, those gibs can create scrape noises if moving against the terrain a certain way, the sounds sometimes never fade.

With lua created effects im talking Lua effects that use VPHYSICS, even with their material set to gmod_silent still create this issue.

**Comment by ZehMatt** [comment]
See https://github.com/Facepunch/garrysmod-issues/issues/4008
