### ISSUE TITLE
Some maps cause permanent memory leaks in Gmod (both client + srcds)

### ISSUE THREAD

**Issue by TeddiO** [Facepunch/garrysmod-issues#4513]
### Details
Version affecting: 2020.05.22, but this has been going on for a while now.
Source Engine 24 (build 7836)

Certain maps when loaded in to memory in Gmod (Win32) cause a permanent memory leak, the cause is not entirely obvious (to me) but I have a sneaking suspicion it's down to how assets packed into a map are getting loaded, as other maps that have little-to-no custom content don't seem to cause this issue as such. 

Although one example has been provided below with surf_pantheon I have found other maps which cause this behaviour but pantheon seems to be one of the worst offenders. While this isn't too much of an issue for servers that mostly stay on one map, gamemodes that change maps frequently can suffer from this fairly badly. I suppose it could be considered a form of denial of service (assuming a bad actor can swap between the two maps over and over somehow) as this would eventually lead to a crash. 

### Steps to reproduce
The map [surf_pantheon](https://gamebanana.com/maps/204884) can be used to show this. 

- Spin up a srcds instance (or a local garrysmod client instance) using sandbox and gm_construct (or flatgrass or a known "good" map) 
- Change to surf_pantheon.
- Change back to your original map (or any other known good map) 
- Change back to surf_pantheon. 

Watch your memory usage keep climbing (about ~700mb each time with surf_pantheon)! 
You can keep repeating the above steps for absolute memory annihilation.

**Comment by mcNuggets1** [comment]
Gmod doesn't clear cache, as far as I'm concerned, while they absolutely should in any cases, CLEAR cache.

**Comment by robotboy655** [comment]
Should be fixed on Dev.

**Comment by Ethorbit** [comment]
This is still an issue. Memory consumption continues to increase with every map loaded until eventually either the srcds process is killed for using too much (players just assume they crashed it), or the server is manually restarted. This is really annoying.
