### ISSUE TITLE
Server settings are not saved on dev branch

### ISSUE THREAD

**Issue by xDShot** [Facepunch/garrysmod-issues#4560]
### Details
Connected to random sandbox server where it had noclip and spawn with weapons disabled. Then quit.
Now all settings are set exactly same as on that server each time I launch the game. I can change them before starting new game, but they are not saved on quitting.

**Comment by GitSparTV** [comment]
Sounds related to the issue when the gamemode convar wasn't restored to the user setting

**Comment by robotboy655** [comment]
They are saved, the issue is that joining a server sets those convars to the server's values (for prediction reasons) and there isn't a clean way of reverting them back and the engine doesn't do so.

I have tried fixing this before the update, but didn't find a good solution for this.

**Comment by GitSparTV** [comment]
Was the solution something like `ConVar->SaveToRestore()` before joining the server and `ConVar->RestoreSaved()` after?

**Comment by xDShot** [comment]
What about settings not being saved?

Also noticed it only happens on Linux. On Windows (Steam Proton) they are saved.

**Comment by robotboy655** [comment]
They use the exact same system as all other convars that save to disk. Ensure your game can write to cfg/config.cfg

**Comment by xDShot** [comment]
Nothing is write protected.

Now happens on Windows as well. And noticed when click new game, set all options, return back to main, new game again, all parameters are reset again...

**Comment by xDShot** [comment]
Seems something to do with stock menu. Installed https://github.com/robotboy655/gmod-lua-menu, problem is gone.

**Comment by robotboy655** [comment]
That issue was fixed probably years ago. Maybe your files are outdated, delete your `lua/` and `/html` folders and verify the game cache.

**Comment by xDShot** [comment]
Still occurs after removing these folders and verifying cache.

**Comment by robotboy655** [comment]
Them not saving is an issue only you have, so there's nothing I can really do about it, without at least knowing how to make it happen on my end. It doesn't happen to me. The only logical conclusion I can make is that something is wrong on your end.

Here's the fix that was done a year ago:
https://github.com/Facepunch/garrysmod/commit/063369e3deba98504479a5b5bc717c57416b3385

**Comment by xDShot** [comment]
Completely wiping content and reinstalling didn't help

**Comment by xDShot** [comment]
Where are gamemode cvars supposed to be stored? And what's a logic behind that js/lua menu stuff like when it decides to set cvars values, etc.

**Comment by viral32111** [comment]
I think they're stored in `cfg/config.cfg`. At least that's what it says for the [`FCVAR_ARCHIVE` flag on the wiki](https://wiki.facepunch.com/gmod/Enums/FCVAR) which is what's meant to make convar changes persistent.

> Save the ConVar value into config.cfg

**Comment by robotboy655** [comment]
It doesn't matter where they are stored, they are only written to disk when you exit the game. That is not your issue.
