### ISSUE TITLE
"CTextureAllocator::GetTextureRect has invalid texture handle! Expect crashes!" Being spammed in console

### ISSUE THREAD

**Issue by ZH-Hristov** [Facepunch/garrysmod-issues#4800]
Not sure what the deal with this is but it seems to happens only when you are looking at the problematic entity. It can be so bad that it spams this thousands of times a second, which can eventually lead to a crash trying to open the console. A way to replicate this would be just to load this save: https://steamcommunity.com/sharedfiles/filedetails/?id=2367623362
Here's a crashdump too:

[hl2_201211_crash_2021_1_22T14_47_24C0.zip](https://github.com/Facepunch/garrysmod-issues/files/5856592/hl2_201211_crash_2021_1_22T14_47_24C0.zip)

**Comment by robotboy655** [comment]
This crash should be fixed in the January 2020 update.

**Comment by VCSoldier** [comment]
Still broken, especially with the Advanced Material tool, doesnt crash my game but it still spams it like hell
CTextureAllocator::GetTextureRect has invalid texture handle! Expect crashes! (x1855)

**Comment by robotboy655** [comment]
I never said the spam was fixed.

**Comment by robotboy655** [comment]
Should be not as spammy.
