### ISSUE TITLE
Problems with mapping in large-scale projects [vis groups and texturing]

### ISSUE THREAD

**Issue by MARK2580** [Facepunch/garrysmod-issues#4811]
### Details
https://www.youtube.com/watch?v=6qL9bhFjzQQ

### Steps to reproduce
When there are already a lot of brushes and vis groups on the map, mapping starts to be a pain. For example, we create a regular cylinder on 32 faces, press enter and it takes an awfully long time to create.
Then we start to apply a texture to it and it takes even longer. Each face is processed for about 3-4 seconds, this is simply not acceptable ! Also, pay attention to what happens to the vis group window. The same exact bugs occur if you start cutting a similar brush or cylinder.
Given that the limits have long been increased, this bug needs to be fixed.

P.S. - If necessary, I will send @Rubat an example of a vmf with resources, I do not want to leave my project in the public domain here.

**Comment by robotboy655** [comment]
Potentially duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4755

Yes a .vmf could be helpful, but do not expect a fix. It may simply be unfixable.

**Comment by MARK2580** [comment]
> Potentially duplicate of #4755
> 
> Yes a .vmf could be helpful, but do not expect a fix. It may simply be unfixable.

I emailed you the archive with a note. I disagree, it has a problem with a large number of objects, but I complain mainly about working with a large number of vis groups.

**Comment by robotboy655** [comment]
Well I cannot reproduce the issue with GMod's Hammer using your `.vmf`.

https://files.facepunch.com/rubat/1b0411b1/ccc.webm

**Comment by MARK2580** [comment]
> Well I cannot reproduce the issue with GMod's Hammer using your `.vmf`.
> 
> https://files.facepunch.com/rubat/1b0411b1/ccc.webm
I don't understand anything, I just checked on a clean build of "x86-x64 - Cromium + 64-bit binaries" and the problem is present.

**Comment by VanderAGSN** [comment]
> Well I cannot reproduce the issue with GMod's Hammer using your `.vmf`.
> 
> https://files.facepunch.com/rubat/1b0411b1/ccc.webm

To reproduce this issue you need to apply nodraw material on faces. The more nodraws in the vmf & the longer it takes to apply them on faces or when cutting the brushes with nodraw

**Comment by robotboy655** [comment]
Should be fixed on Dev.

**Comment by MARK2580** [comment]
It got a little better, but changing the texture from nodraw to any other still occurs with a noticeable delay 🙄

**Comment by robotboy655** [comment]
Not on my end. 🤷 This is as good as it's gonna get.

**Comment by MARK2580** [comment]
> Not on my end. 🤷 This is as good as it's gonna get.
> 
> The UI should no longer be rebuilding 32 times per texture application.

https://youtu.be/Bn7exJDUrF4
Yes, now of course these operations occur about 3 times faster. But there is still a noticeable hitch. I click during the mouse gesture, unfortunately my recording program does not support effects when clicked. Thanks for trying.

**Comment by robotboy655** [comment]
That is down to your PC. I have pretty much 0 issues with this now. The initial issue on your video also took longer per texture application than it did for me.

**Comment by MARK2580** [comment]
> That is down to your PC. I have pretty much 0 issues with this now. The initial issue on your video also took longer per texture application than it did for me.

Well, sorry, I don't have an i9-9999K and an rtx 3080Ti.... I didn't know that to work with the 2007 engine, you need such power...
I have an i5-7600K/32gb ddr4/gtx 1060 6gb

**Comment by robotboy655** [comment]
Huh, that is strange. My hardware is much older/worse (i7-4702HQ, GTX 850M, no SSDs), but it is still faster for me than it is for you.

Compare this before fix for me and your original video:
https://files.facepunch.com/rubat/1b0811b1/before_fix.mp4

Yeah there's still a small hitch after fix, (i think it recomputes which object belongs to which group all objects on the map), but it is definitely usable now where you can argue it wasn't before.

This being said, I have made some more changes to Hammer:
```
Further optimize Hammer auto visgroup rebuilding when applying tool textures
Fixed major hang when opening Texture Application Tool with many objects selected
Fixed alignment/size of Texture Shift/Scale Y axis text boxes to match the other text boxes, now its perfect
```

**Comment by MARK2580** [comment]
You have 8 threads, maybe it somehow affects. Also, I have the game itself installed on a regular HDD 7200 / SATAIII. We are waiting for updates ...

**Comment by MARK2580** [comment]
Now everything really works fast. You can when you want 😁
https://youtu.be/J9gznzxvxDY
