### ISSUE TITLE
sv_parallel_* commands seems to have no effect on the 64 bit branch

### ISSUE THREAD

**Issue by FredyH** [Facepunch/garrysmod-issues#5310]
### Details
The two commands
```
sv_parallel_sendsnapshot 1
sv_parallel_packentities 1
```
do not make any difference when enabled on the 64 bit branch of gmod (both the 32 and 64 bit versions of that branch).
These two commands give servers quite a significant performance boost since it allows some parts of the networking to be run on a separate thread, which is visible by CPU usage going up to 125% rather than 100% (100% = one core).
Please note that I only tested this on Linux.

### Steps to reproduce
Install the 64 bit branch of gmod and run a server that is running at or near capacity. The server will never use more than one core.
Install the 32 bit branch, do the same and notice that the usage will exceed that of a single core by up to 25%.

**Comment by RaphaelIT7** [comment]
I've looked into this a bit, and it seems like the thread pool is not started properly.

It's probably done the same way as on the 32x, which doesn't work on the 64x.

How it's probably done currently:
```cpp
// host.cpp
// void Host_Init( bool bDedicated )

[...]
ThreadPoolStartParams_t startParams;
[...]
if ( g_pThreadPool )
  g_pThreadPool->Start( startParams, "CmpJob" );
```

How it should be done:
```cpp
// host.cpp
// void Host_Init( bool bDedicated )
[...]
ThreadPoolStartParams_t startParams;
[...]
if ( g_pThreadPool )
  startParams.bEnableOnLinuxDedicatedServer = bDedicated;
  g_pThreadPool->Start( startParams );
```

I tested it with a module, and it solved the bug.
If someone needs it the module here u have the code (Only works for Linux):

```cpp
#include <GarrysMod/Lua/Interface.h>
#include <GarrysMod/FactoryLoader.hpp>
#include "platform.h"

#define DEDICATED
#include "vstdlib/jobthread.h"

GMOD_MODULE_OPEN()
{
	ThreadPoolStartParams_t startParams;
	startParams.bEnableOnLinuxDedicatedServer = true;
	g_pThreadPool->Start(startParams);

	return 0;
}

GMOD_MODULE_CLOSE()
{
	return 0;
}
```

**Comment by oninoni** [comment]
Honestly I feel like it is also not working on the default branch of the game.
I cannot detect any changes in performance when enabling the convars.

Has anybody actually seen a big performance improvement?

**Comment by RaphaelIT7** [comment]
It works fine on the default branch of the game. If it was broken, you would never go above 100%.

sv_parallel_sendsnapshot is disabled by default. 
It could be that you don't see an Improvement because you didn't enable it.

**Comment by robotboy655** [comment]
Should be resolved.

**Comment by FredyH** [comment]
I just tested it on my server and it seems to still not have any effect @robotboy655.
Maybe someone else can also confirm?

**Comment by RaphaelIT7** [comment]
![image](https://github.com/user-attachments/assets/20ad7fbc-3d3e-48ce-a752-4ad355172523)
Seems like this exact issue came back. (The solution still works, so the threadpool isn't started properly again)

**Comment by robotboy655** [comment]
Try again when it next updates and let me know if it is fixed.
