### ISSUE TITLE
DTextEntry incorrect caret pos by mouse click and offset in SetDrawLanguageIDAtLeft

### ISSUE THREAD

**Issue by TIMONz1535** [Facepunch/garrysmod-issues#5611]
### 1) Caret pos by mouse click

When you type large text in **DTextEntry**, your visual position follows the caret (the caret is always on the right). If you erase the text more than you can see, the caret moves, but your visual position does not change, it stays in the same place. So when you click with **LMB**, the caret pos is set to further than the text size. If you type another symbol, the line will be filled with garbage (the last character before erasing).
**It is expected that the visual position also moves to the left to the caret pos, even if you call `SetCaretPos(0)`.**

**Steps:**
- Type some long text
- Select the big part of the text or press **Crtl+A**, and erase it with **Backspace** or **Delete**
- Press **LMB** at the entry line, you can see how the caret has moved
- Type some another symbol, this will fill the line with garbage

https://github.com/Facepunch/garrysmod-issues/assets/7351599/0cdd915d-6513-406c-9209-5120e0b0856b

### 2) SetDrawLanguageIDAtLeft

When you use the `Panel:SetDrawLanguageIDAtLeft`, your mouse cursor pos doesn't correspond to the caret pos, its are shifted by language label.

https://github.com/Facepunch/garrysmod-issues/assets/7351599/8113aa49-0e97-474e-8436-f2790d8ddd70

### Test code for both cases

```lua
local frame = vgui.Create("DFrame")
frame:SetSize(400, 200)
frame:Center()
frame:MakePopup()

local textEntry = vgui.Create("DTextEntry", frame)
textEntry:Dock(TOP)
-- textEntry:SetDrawLanguageIDAtLeft(true)

local label1 = vgui.Create("DLabel", frame)
label1:Dock(TOP)
local label2 = vgui.Create("DLabel", frame)
label2:Dock(TOP)
local label3 = vgui.Create("DLabel", frame)
label3:Dock(TOP)

frame.Think = function()
	label1:SetText("Text size: " .. #textEntry:GetText())
	label2:SetText("Value size: " .. #textEntry:GetValue())
	label3:SetText("Caret pos: " .. textEntry:GetCaretPos())
end
```

**Comment by robotboy655** [comment]
Should be fixed on `dev` beta.

**Comment by TIMONz1535** [comment]
Case 1 "Caret pos by mouse click" still not fixed

```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 19:00:21 Mar 21 2024 (9246) (4000)
GMod version 2024.03.21, branch: unknown, multicore: 1
Windows 32bit
```

https://github.com/Facepunch/garrysmod-issues/assets/7351599/63aabdae-3227-48a8-bc35-866c862f54c5

Also maybe not a bug but I noticed that with `SetDrawLanguageIDAtLeft`, switching the language or `SetCaretPos` to the end (I press Alt on video) after shifting carriage to the left, causes the carriage to be visually beyond the right boundary.

https://github.com/Facepunch/garrysmod-issues/assets/7351599/8320010e-45b9-4837-bc99-fd636864dc11

```lua
local textEntry = vgui.Create("DTextEntry", frame)
textEntry:Dock(TOP)
textEntry:SetDrawLanguageIDAtLeft(true)

local label1 = vgui.Create("DLabel", frame)
label1:Dock(TOP)
local label2 = vgui.Create("DLabel", frame)
label2:Dock(TOP)
local label3 = vgui.Create("DLabel", frame)
label3:Dock(TOP)
local label4 = vgui.Create("DLabel", frame)
label4:Dock(TOP)

frame.Think = function()
	label1:SetText("Text size: " .. #textEntry:GetText())
	label2:SetText("Value size: " .. #textEntry:GetValue())
	label3:SetText("Caret pos: " .. textEntry:GetCaretPos())
	label4:SetText("Text len utf8: " .. utf8.len(textEntry:GetText()))

	if input.IsKeyDown(KEY_LALT) then
		textEntry:SetCaretPos(utf8.len(textEntry:GetText()))
	end
end
```

**Comment by robotboy655** [comment]
I will fix the first issue, I don't think the second one is worth the effort, you just continue typing and it will scroll to the caret for you.
