### ISSUE TITLE
Materials unloading even though decals using them are present

### ISSUE THREAD

**Issue by ZH-Hristov** [Facepunch/garrysmod-issues#5756]
I'm working on a better Paint tool using DecalEx that allows for size scaling and using any material that aint LightMappedGeneric, but I ran into a bit of a gamebreaker.

At seemingly random intervals (I feel like it's a timer + many materials loaded combo), the game will unload materials, causing the decals to turn into missingtexture squares, even though there are decals present that are using them.

Shouldn't be a mat problem. All the mats here have been autoconverted by me to VertexLitGeneric using a Python script. Which materials get unloaded seems to be random. Viewing the materials in something like Asset Browser brings them back from checkerboard hell until the next unload.

I don't know if by chance or if there's some Source quirk, but the 2 times I replicated the unload 5 of the materials stayed both times, perhaps due to being DecalModulate? (The L4D2 safehouse grafitti decals, the arrows below them and the bloodstain on the right)

Before:
![unshitted](https://github.com/Facepunch/garrysmod-issues/assets/7620140/1d757530-2c56-466d-bf62-be0ccb6ff04d)
After:
![shitted](https://github.com/Facepunch/garrysmod-issues/assets/7620140/819cb4ae-73ce-4f49-87c4-ba4a0ee7b002)

**Comment by robotboy655** [comment]
A few questions:
1) Does this happen on NONE beta?
2) Have you tested any of the other beta branches?
3) How long is this "random interval" on average?
4) How exactly can I reproduce this issue? Is your tool available anywhere? Is it just decals on props? Does it happen with the normal Paint tool decals?

**Comment by ZH-Hristov** [comment]
> A few questions:
> 
>     1. Does this happen on NONE beta?
> 
>     2. Have you tested any of the other beta branches?
> 
>     3. How long is this "random interval" on average?
> 
>     4. How exactly can I reproduce this issue? Is your tool available anywhere? Is it just decals on props? Does it happen with the normal Paint tool decals?

1. I've only tested on x64
2. Nope
3. Doesn't seem consistent, I feel like the best way is to use the Asset Browser addon and just open random material folders to load a bunch of new mats, then I think you might have to move around a bit.
4. Uploaded the tool to Git https://github.com/ZH-Hristov/superpaint

Haven't tested with the normal Paint tool decals.

**Comment by ZH-Hristov** [comment]
I know I'm not caching the materials myself, but I was hoping the engine would take care of that internally, since there are decals present with the loaded materials.

**Comment by ZH-Hristov** [comment]
I wonder if perhaps any of the decal flags would have an effect here? https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/engine/decal_private.h#L59-L74

**Comment by ZH-Hristov** [comment]
Forgot to mention the console spam when a mat gets unloaded/unreferenced
![Screenshot 2024-02-29 161219](https://github.com/Facepunch/garrysmod-issues/assets/7620140/d7b2b64b-6b1e-405d-b248-1f664f0a2ec8)
.

**Comment by ZH-Hristov** [comment]
An instant way to get an unload is to remove the LightmappedGeneric check from the tool and try to spawn a decal with a material that uses that shader. It will clip really badly and after about half a second will turn into missingtexture

**Comment by robotboy655** [comment]
Should be fixed on dev.

**Comment by ZH-Hristov** [comment]
Just tested, still happens. The fix is present on x64 right?

**Comment by ZH-Hristov** [comment]
Vid of bug in action from decal placement to unload:
https://github.com/Facepunch/garrysmod-issues/assets/7620140/d2abf17e-e877-441f-b081-bd701b6dbaf2
Had to compress for size limits so quality is ass but this basically shows the repro process. Just splat a bunch of materials on it and then keep scrolling with a material browser until it happens. I placed decals/dark, decals/light and that one decal mat that for some reason is not affected on the right

**Comment by robotboy655** [comment]
No, the fix is dev only right now.

**Comment by ZH-Hristov** [comment]
Alright, yeah. Just tried dev and I can't seem to reproduce it so it seems like it's fixed.
