### ISSUE TITLE
Support cyrillic fonts

### ISSUE THREAD

**Issue by Roni-sl** [Facepunch/garrysmod-issues#842]
Make a support of cyrillic letters in fonts please.
Now it's don't work: 
![2013](https://f.cloud.github.com/assets/1414051/2238060/13a35944-9bda-11e3-9dbd-1fd79101bbd7.jpg)

**Comment by willox** [comment]
This should be fixed on the dev branch for Windows in a couple of hours.

**Comment by Kefta** [comment]
:+1:

**Comment by willox** [comment]
This should be fixed on the dev branch for OSX in a couple of hours. :rocket:

**Comment by 00875** [comment]
![2016-04-14_19-04_garry s mod](https://cloud.githubusercontent.com/assets/6339511/14527295/2baca7aa-0273-11e6-96f0-5aab0ee6d095.jpg)
Still not fixed

**Comment by bigdogmat** [comment]
I believe it's still fixed on dev branch, though it was rolled back from last update because of unexpected bugs. Not sure if it's coming next update or not

**Comment by willox** [comment]
Are you on the dev or prerelease branch? If so, what font is that?

**Comment by 00875** [comment]
Roboto

**Comment by robotboy655** [comment]
Font changes were reverted due to some unexpected problems, try the Dev/Pre-release branch.

**Comment by 00875** [comment]
![2016-04-29_19-45_garry s mod april](https://cloud.githubusercontent.com/assets/6339511/14916202/44f8f13e-0e42-11e6-91b9-1229e2c999f8.jpg)

Ubuntu Light:
![2016-04-29_19-44_garry s mod](https://cloud.githubusercontent.com/assets/6339511/14916205/48b3146c-0e42-11e6-800a-a86d37f98f49.jpg)

Roboto:
![2016-04-29_19-46_garry s mod](https://cloud.githubusercontent.com/assets/6339511/14916223/6be421f6-0e42-11e6-855c-3d6b917abbec.jpg)

Or something i do not understand?
Fonts supports crylic letters

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Structures/FontData 

See the extended option.

**Comment by 00875** [comment]
Many thanks!
![2016-04-29_19-54_garry s mod](https://cloud.githubusercontent.com/assets/6339511/14916373/88353952-0e43-11e6-82ae-180ba6f24efc.jpg)

**Comment by art-gur** [comment]
Use this code to create a new font:
`surface.CreateFont( "rsLite", {
font = "Segoe UI Light",
extented = true,
size = 21,
weight = 300 } )`
But result is strange: russian symbols doen't rendering:
![20170125201137_1](https://cloud.githubusercontent.com/assets/3049963/22294614/1a158ab4-e33e-11e6-8b34-9ee74f5084ef.jpg)

**Comment by bmwalters** [comment]
@art-gur `extented` should be `extended`

**Comment by uRandomAlex** [comment]
May be close this already? @robotboy655 @willox Someone?

**Comment by robotboy655** [comment]
Why do you want us to close an issue that isn't completely fixed?

**Comment by uRandomAlex** [comment]
I thought it is.

**Comment by MostRush** [comment]
someday fix it?

**Comment by Narshalbarsh** [comment]
If extended is intentionally disabled on the linux client, can we get some kind of config to opt in? Or is there some reason this is still disabled? I haven't noticed any issues with it patched to enable it
